apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-ibm
spec:
  config:
    ignition:
      version: 3.3.0
    storage:
      files:
        - path: /usr/local/bin/powersmt
          overwrite: true
          mode: 0700
          filesystem: root
          contents:
            source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKZXhwb3J0IFBBVEg9L3Jvb3QvLmxvY2FsL2Jpbjovcm9vdC9iaW46L3NiaW46L2JpbjovdXNyL2xvY2FsL3NiaW46L3Vzci9sb2NhbC9iaW46L3Vzci9zYmluOi91c3IvYmluCmV4cG9ydCBLVUJFQ09ORklHPS92YXIvbGliL2t1YmVsZXQva3ViZWNvbmZpZwpDT1JFUFM9JCgvYmluL2xzY3B1IHwgL2Jpbi9hd2sgLUY6ICcgJDEgfiAvXkNvcmVcKHNcKSBwZXIgc29ja2V0JC8ge3ByaW50ICQyfSd8L2Jpbi94YXJncykKU09DS0VUUz0kKC9iaW4vbHNjcHUgfCAvYmluL2F3ayAtRjogJyAkMSB+IC9eU29ja2V0XChzXCkkLyB7cHJpbnQgJDJ9J3wvYmluL3hhcmdzKQpsZXQgVE9UQUxDT1JFUz0kQ09SRVBTKiRTT0NLRVRTCk1BWFRIUkVBRFM9JCgvYmluL2xzY3B1IHwgL2Jpbi9hd2sgLUY6ICcgJDEgfiAvXkNQVVwoc1wpJC8ge3ByaW50ICQyfSd8L2Jpbi94YXJncykKbGV0IE1BWFNNVD0kTUFYVEhSRUFEUy8kVE9UQUxDT1JFUwpDVVJSRU5UU01UPSQoL2Jpbi9sc2NwdSB8IC9iaW4vYXdrIC1GOiAnICQxIH4gL15UaHJlYWRcKHNcKSQvIHtwcmludCAkMn0nfC9iaW4veGFyZ3MpCndoaWxlIDogCmRvCklTTk9ERURFR1JBREVEPSQoL2Jpbi9vYyBnZXQgbm9kZSAkSE9TVE5BTUUgLW8geWFtbCB8L2Jpbi9ncmVwIG1hY2hpbmVjb25maWd1cmF0IGlvbi5vcGVuc2hpZnQuaW8vcmVhc29uIHwvYmluL2dyZXAgInVuZXhwZWN0ZWQgb24tZGlzayBzdGF0ZSB2YWxpZGF0aW5nIikKU01UTEFCRUw9JCgvYmluL29jIGdldCBub2RlICRIT1NUTkFNRSAtTCBTTVQgLS1uby1oZWFkZXJzIHwvYmluL2F3ayAne3ByaW50ICQ2fScgKQogIGlmIFtbIC1uICRTTVRMQUJFTCBdXQogICAgdGhlbgogICAgICBjYXNlICRTTVRMQUJFTCBpbgogICAgICAgIDEpIFRBUkdFVFNNVD0xCiAgICAgIDs7CiAgICAgICAgMikgVEFSR0VUU01UPTIKICAgICAgOzsKICAgICAgICA0KSBUQVJHRVRTTVQ9NAogICAgICA7OwogICAgICAgIDgpIFRBUkdFVFNNVD04CiAgICAgIDs7CiAgICAgICAgKikgVEFSR0VUU01UPSRDVVJSRU5UU01UIDsgZWNobyAiU01UIHZhbHVlIG11c3QgYmUgMSwgMiwgNCwgb3IgOCBhbmQgc21hbGxlciB0aGFuIE1heGltdW0gU01ULiIKICAgICAgOzsKICAgICAgZXNhYwogICAgZWxzZQogICAgICBUQVJHRVRTTVQ9JE1BWFNNVAogIGZpCiAgaWYgW1sgLW4gJElTTk9ERURFR1JBREVEIF1dCiAgICB0aGVuCiAgICAgIHRvdWNoIC9ydW4vbWFjaGluZS1jb25maWctZGFlbW9uLWZvcmNlCiAgZmkKQ1VSUkVOVFNNVD0kKC9iaW4vbHNjcHUgfCAvYmluL2F3ayAtRjogJyAkMSB+IC9eVGhyZWFkXChzXCkgcGVyIGNvcmUkLyB7cHJpbnQgJDIgfSd8L2Jpbi94YXJncykKICBpZiBbWyAkQ1VSUkVOVFNNVCAtbmUgJFRBUkdFVFNNVCBdXQogICAgdGhlbgogICAgICBJTklUT05USFJFQUQ9MAogICAgICBJTklUT0ZGVEhSRUFEPSRUQVJHRVRTTVQKICAgICAgaWYgW1sgJE1BWFNNVCAtZ2UgJFRBUkdFVFNNVCBdXQogICAgICAgIHRoZW4KICAgICAgICAgIHdoaWxlIFtbICRJTklUT05USFJFQUQgLWx0ICRNQVhUSFJFQURTIF1dCiAgICAgICAgICBkbwogICAgICAgICAgICBPTlRIUkVBRD0kSU5JVE9OVEhSRUFECiAgICAgICAgICAgIE9GRlRIUkVBRD0kSU5JVE9GRlRIUkVBRAogICAgICAgICAgICB3aGlsZSBbWyAkT05USFJFQUQgLWx0ICRPRkZUSFJFQUQgXV0KICAgICAgICAgICAgZG8KICAgICAgICAgICAgICAvYmluL2VjaG8gMSA+IC9zeXMvZGV2aWNlcy9zeXN0ZW0vY3B1L2NwdSRPTlRIUkVBRC9vbmxpbmUKICAgICAgICAgICAgICBsZXQgT05USFJFQUQ9JE9OVEhSRUFEKzEKICAgICAgICAgICAgZG9uZQogICAgICAgICAgICBsZXQgSU5JVE9OVEhSRUFEPSRJTklUT05USFJFQUQrJE1BWFNNVAogICAgICAgICAgICB3aGlsZSBbWyAkT0ZGVEhSRUFEIC1sdCAkSU5JVE9OVEhSRUFEIF1dCiAgICAgICAgICAgIGRvCiAgICAgICAgICAgICAgL2Jpbi9lY2hvIDAgPiAvc3lzL2RldmljZXMvc3lzdGVtL2NwdS9jcHUkT0ZGVEhSRUFEL29ubGluZQogICAgICAgICAgICAgIGxldCBPRkZUSFJFQUQ9JE9GRlRIUkVBRCsxCiAgICAgICAgICAgIGRvbmUKICAgICAgICAgICAgbGV0IElOSVRPRkZUSFJFQUQ9JElOSVRPRkZUSFJFQUQrJE1BWFNNVAogICAgICAgICAgZG9uZQogICAgICAgIGVsc2UKICAgICAgICAgIGVjaG8gIlRhcmdldCBTTVQgbXVzdCBiZSBzbWFsbGVyIG9yIGVxdWFsIHRoYW4gTWF4aW11bSBTTVQgc3VwcG9ydGVkIgogICAgICBmaQogIGZpCiAgL2Jpbi9zbGVlcCAzMApkb25lCg==
        - path: /etc/systemd/system/powersmt.service
          overwrite: true
          mode: 0644
          filesystem: root
          contents:
            source: data:text/plain;charset=utf-8;base64,W1VuaXRdCkRlc2NyaXB0aW9uPVBPV0VSU01UCkFmdGVyPW5ldHdvcmstb25saW5lLnRhcmdldApbU2VydmljZV0KRXhlY1N0YXJ0PSIvdXNyL2xvY2FsL2Jpbi9wb3dlcnNtdCIKW0luc3RhbGxdCldhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0Cg==
        - path: /etc/motd
          overwrite: true
          mode: 0644
          filesystem: root
          append:
            source: data:text/plain;charset=utf-8;base64,SGkgdGhlcmUhCg==
    systemd:
      units:
        - name: powersmt.service
          enabled: true            
